import React from "react";
import SignUpPageOtherHalf from "@auth/sign-up/_components/SignUpPageOtherHalf";
import AuthStageIndicator from "@auth/sign-up/_components/SignUpStageIndicator";
import { AuthProvider } from "@auth/context/AuthContext";

export const metadata: any = {
  title: "rabbitbrain · Create your account ",
  description: "Generated by create next app",
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <AuthProvider>
      <div className="relative flex min-h-screen w-full overflow-hidden">
        {/* Full Background */}
        <div className="absolute inset-0 h-full z-0">
          <SignUpPageOtherHalf />
        </div>
        {/* Form & Stage Indicator */}
        <div className="relative z-10 flex items-start p-6 w-full max-w-2xl h-screen">
          <div className="flex h-full flex-col justify-center w-full bg-background rounded-lg px-6 py-4 md:px-20">
            {children}
            <AuthStageIndicator outOf={3} />
          </div>
        </div>
      </div>
    </AuthProvider>
  );
};

export default AuthLayout;
