import React from "react";
import AuthImageSection from "@/app/(authentication)/sign-up/_components/AuthImageSection";
import AuthStageIndicator from "@auth/sign-up/_components/SignUpStageIndicator";
import { AuthProvider } from "@auth/context/AuthContext";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "rabbitbrain · Create your account",
  description: "Generated by create next app",
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <AuthProvider>
      <div className="flex w-full h-screen">
        {/* Sign Up Page Half (Image & Form Section) */}
        <div className="w-1/2 p-5 md:block hidden">
          <div className="w-full h-full rounded-xl overflow-hidden">
            <AuthImageSection />
          </div>
        </div>
        {/* Form Section */}
        <div className="w-full px-1 md:w-1/2 h-full flex items-center justify-center relative pt-6 pb-1">
          <div className="flex flex-col h-full w-full max-w-md relative">
            <div className="flex-grow">{children}</div>
            <div className="w-full">
              <AuthStageIndicator outOf={3} authAction="sign-up" />
            </div>
          </div>
        </div>
      </div>
    </AuthProvider>
  );
};

export default AuthLayout