import React, { useEffect } from "react";
import SignUpPageOtherHalf from "./sign-up/_components/SignUpPageOtherHalf";
import AuthStageIndicator from "./sign-up/_components/SignUpStageIndicator";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: any = {
  title: "Einv | Create your account",
  description: "Generated by create next app",
};

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <AuthProvider>
      <div className="flex min-h-screen w-full flex-row overflow-hidden">
        <div className="flex flex-col md:flex-row flex-1">
          {/* Left Side */}
          <div className="flex w-full flex-1 justify-center items-center p-4 md:p-8 md:pb-4">
            <div className="flex flex-col h-full justify-between w-full max-w-lg">
              {children}
              <AuthStageIndicator outOf={3} />
            </div>
          </div>
          {/* Right Side */}
          <div className="hidden lg:flex lg:w-1/2 items-center justify-center">
            <SignUpPageOtherHalf />
          </div>
        </div>
      </div>
    </AuthProvider>
  );
};

export default AuthLayout;
